<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->head?>
        <?php echo $this->headTitle($this->translate('Bulk SMS'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/intlTelInput.css'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/jquery-ui.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.mod.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.mod.css'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-datetimepicker.min.css')?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/jquery.validate.min.js'))      
            ->prependFile($this->basePath("js/jquery.nicefileinput.min.js"))
            ->prependFile($this->basePath('js/intlTelInput.min.js'))    
            ->prependFile($this->basePath('js/bootstrap.js'))
            ->prependFile($this->basePath() . '/js/bootstrap-datetimepicker.min.js')
            ->prependFile($this->basePath() . '/js/moment.min.js')
            ->prependFile($this->basePath() . '/js/transition.js')
            ->prependFile($this->basePath() . '/js/collapse.js')
            ->prependFile($this->basePath('js/jquery-ui.js'))    
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

        
        
    </head>
    <body>
        
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                
                <div class="row navbar-header">
                    
<!--                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>-->
                    <div class="navbar-brand">
                        <a href="#menu-toggle" style="color: white;" class="btn btn-side-panel" id="menu-toggle"><span class="glyphicon glyphicon-list"></span></a>
                        <a href="/client/home/index"><img src="<?php echo $this->basePath('img/logo_header.png') ?>" alt="Bulk SMS"/>&nbsp;<?php echo $this->translate('') ?></a>
                    </div>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav  pull-right">
                        <!--<li class="active"><a href="<?php // echo $this->url('home') ?>"><?php // echo $this->translate('Home') ?></a></li>-->
                        <li class="dropdown">
                            <a href="" data-toggle='dropdown'><span class="glyphicon glyphicon-user"></span> <?php  echo $this->user_data->first_name.' '.$this->user_data->last_name; ?></a>
                            <ul class="dropdown-menu">
                                <li><a role="menuitem" tabindex="-1" href="/client/home/password">Change Password</a></li>
                            </ul>
                        </li>
                        
                        <li ><a href="/client/signin/logout"><span class="glyphicon glyphicon-log-out"></span> <?php  echo $this->translate('Logout') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        
        
        <div class="container-fluid">
            <div id="wrapper">

                <!-- Sidebar -->
                <div id="sidebar-wrapper">
                    <ul class="sidebar-nav">
<!--                        <li class="sidebar-brand">
                            <a href="/">
                                <img src="<?php // echo $this->basePath('img/logo_side_panel.png') ?>" alt="Bulk SMS"/>
                            </a>
                        </li>-->
                        <li style="margin-top: 50px;">
                            <div>
                                <a href="/client/home/index">
                                    <span class="glyphicon glyphicon-home">
                                    </span> Home
                                </a>
                            </div>
                        </li>
                        <li><div>
                            <a href="/client/subscription/index">
                                <span class="glyphicon glyphicon-list">
                                </span> 
                                Subscriptions
                            </a>
                            <!--<a href="/client/subscription/add"> Add List<span class="glyphicon glyphicon-plus"></span></a>-->
                            </div>
                        </li>
                        <li>
                            <div>
                            <a href="/client/campaign/index"> 
                                <span class="glyphicon glyphicon-flag">
                                </span> Campaigns
                            </a>
                            <!--<a href="/client/campaign/add"> Add Campaign<span class="glyphicon glyphicon-plus"></span></a>-->
                            </div>
                        </li>
                        <li><div>
                            <a href="#">
                                <span class="glyphicon glyphicon-earphone">
                                </span> 
                                Contact
                            </a>
                            </div>
                        </li>
                        <li><div>
                            <a href='/client/signin/logout'>
                                <span class="glyphicon glyphicon-log-out">
                                </span> 
                                Logout
                            </a>
                            </div>
                        </li>
                    </ul>
                </div>
                
        
            </div>
            
            <div id = "page-content-wrapper" class="container" style="background: #fff;min-height: 600px;">
                <div class="col-lg-10 col-lg-offset-2">
                        <?php echo $this->content; ?>
                </div>
                    
                </div>
            
        </div>
                   
        <div class="container" style="max-height: 60px;">

            <hr style="border-color: #E95E45">
            <footer>
                <table class="table footer-table">
                    <tr>
                        <th>About Us</th>
                        <th>Services</th>
                        <th>FAQ</th>
                        <th>Help</th>
                        <th class="pull-right"><p>&copy; 2005 - <?php echo date('Y') ?> by Some Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p></th>
                    </tr>
                </table>

            </footer>
        </div> <!-- /container -->
            
        <?php echo $this->inlineScript() ?>
        <script>
        $("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
            $("#page-content-wrapper > div").toggleClass('col-lg-offset-2');
            $("#page-content-wrapper > div").toggleClass('col-lg-offset-1');
        });
        </script>
    </body>
</html>
