<script>
$(document).ready(function(){
   $('.form-group > label').css('color', '#E95E45'); 
   $('button').addClass('btn-sm');
   $('input').addClass('input-sm');
   $('.form-group').css('margin-top','5px');
   
});    
</script>

<div class="col-lg-6" >    
<?php
$token = $this->signup_token;
$form = $this->form;
$form->prepare();
$form->setAttribute('action', "/client/home/process");

$form->setAttribute('method', 'post');
$form->setAttribute('enctype','multipart/form-data');
$form->setAttribute('class', 'form-horizontal');

echo $this->form()->openTag($form);
?>
    <div>
        <div class="form-group">
            <label></label>
            <div>
                <h3 style="color: #E95E45"><b>Set new password</b></h3>
            </div>
        </div>
        <div class="form-group">
            <label></label>
            <div>
                <p style="color: red"><?php echo $this->error;?></p>
            </div>
        </div>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('password')); ?>
            <div><?php 
                echo $this->formElement($form->get('password'));
                echo $this->formElementErrors($form->get('password'));
            ?></div>
        </div>
        
        <div class="form-group">
            <?php echo $this->formLabel($form->get('confirm_password')); ?>
            <div><?php 
                echo $this->formElement($form->get('confirm_password'));
                echo $this->formElementErrors($form->get('confirm_password'));
            ?></div>
        </div>
        
        <div class="form-group">
            <label></label>
            <div><?php 
            echo $this->formElement($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
        ?></div>
        </div>
        
        <div class="form-group">
            <label> </label>
            <div>
                <button name="Cancel"  onclick="history.go(-1); return false;" class="btn btn-sm " value="Cancel">Cancel</button>
            </div>
        </div>
        
    </div>
</div>

<?php echo $this->form()->closeTag() ?>