<script>
$(function(){

   var message = '<?php echo $this->flashMessenger()->render();?>';
    
    if ( message !== "" ){
        
        $('#dialog > p').html(message);
        $('#dialog').dialog({ modal: true,
                buttons: {
                Ok: function() {
                  $( this ).dialog( "close" );
                }
              }
        });
        
        
    }
    
    $('.ui-dialog-buttonset').addClass('col-md-12');
    $('.ui-dialog-buttonset > button').addClass('btn btn-sm col-sm-2 pull-right');     
});
</script>
<ul class="breadcrumb">
    <li><a href="<?php echo $this->url(NULL, array('controller' => 'home', 'action' => 'index'));?>">Home</a></li>
    <li><a href="<?php echo $this->url(NULL, array('controller' => 'subscription', 'action' => 'index'));?>">Subscriptions</a></li>
    
</ul>
<div id="dialog" title="Alert!">
    <p></p>
</div>
<div class="row">
    
    <h3><div class="col-lg-10">Subscriptions </div>
        <div class="col-lg-2" style="margin-bottom: 3px;">
        <button class="btn btn-sm pull-right" onclick="window.location.href='<?php echo $this->url(NULL,
        array('controller' => 'subscription', 'action'=>'add'));?>'"><span class="glyphicon glyphicon-plus"></span> Add New
        </button>
        </div>    
    </h3>
</div>


  
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Package</th>
            <th>Creation Date</th>
            <th>Expiry Date</th>
            <th>SMS Quota</th>
            <th>Action</th>
        </tr>
    </thead>
    <?php foreach ($this->paginator as $subscription) : ?>
    <tr>
        <td><?php echo $subscription->list_name;?></td>
        <td><?php echo $subscription->package_name;?></td>
        <td><?php echo $subscription->created_at;?></td>
        <td><?php echo $subscription->expiry_date;?></td>
        <td><?php echo $subscription->sent_sms.'/'.$subscription->sms_quota;?></td>
        
        
        <td>
            <a title='Edit' href="<?php echo $this->url(NULL, array( 'controller' => 'subscription', 'action'=>'change', 'id' => $subscription->list_id));?>"><span class="glyphicon glyphicon-edit"></span></a>   
            <a title="Subscribers list" href="<?php echo $this->url(NULL, array( 'controller' => 'subscription', 'action'=>'more', 'id' => $subscription->list_id));?>"><span class="glyphicon glyphicon-list-alt"></span></a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>    

<?php if ( $this->paginator->count() > 0 ) {?>
 <div align="center">
    <ul class="pagination">
        <?php 
            $currentPage = $this->paginator->getCurrentPageNumber();
            $lastPage = $this->paginator->count();
            $id = 1;
            if ( $lastPage < 10 ){
                $start_pos = 1;
                $last_pos = $lastPage;
            }else{
                if ( $currentPage < 10 ){
                    $start_pos = 1;
                    $last_pos = 10;
                }else if ( $currentPage > $lastPage - 10){
                    $start_pos = $lastPage-10;
                    $last_pos = $lastPage;
                } else {
                    $start_pos = $currentPage-5;
                    $last_pos = $currentPage+5;
                }
            }
        ?>
        <li><a href="<?php echo $this->url(NULL, 
                            array("controller" => 'subscription', 
                                'action' => 'index', 
                                'id' => $id, 
                                'page' => 1,
                                'search_string' => $search_string,
                            ));?>" <?php if ( $currentPage == 1 ) echo 'class=\'not-active\'';?>> << </a></li>     
        <li><a href="<?php echo $this->url(NULL, 
                            array("controller" => 'subscription', 
                                'action' => 'index', 
                                'id' => $id, 
                                'page' => $currentPage-1,
                                'search_string' => $search_string,
                            ));?>" <?php if ( $currentPage == 1 ) echo 'class=\'not-active\'';?>> < </a></li>     
        <?php
            for ($page_number=$start_pos; $page_number<= $last_pos; $page_number++){
        ?>
        <li class="<?php if ($page_number == $currentPage) echo "active";?>"><a href="<?php echo $this->url(NULL, 
                            array("controller" => 'subscription', 
                                'action' => 'index', 
                                'id' => $id, 
                                'page' => $page_number,
                                'search_string' => $search_string,
                            ));?>" ><?php echo $page_number;?></a></li>
        <?php }?>
        <li><a href="<?php echo $this->url(NULL, 
                            array("controller" => 'subscription', 
                                'action' => 'index', 
                                'id' => $id, 
                                'page' => $currentPage+1,
                                'search_string' => $search_string,
                            ));?>" <?php if ( $currentPage == $lastPage ) echo 'class=\'not-active\'';?>>> </a></li>     
        <li><a  href="<?php if ( $currentPage != $lastPage ) echo $this->url(NULL, 
                            array("controller" => 'subscription', 
                                'action' => 'index', 
                                'id' => $id, 
                                'page' => $lastPage,
                                'search_string' => $this->search_string,
                            ));?>" <?php if ( $currentPage == $lastPage ) echo 'class=\'not-active\'';?>> >> </a></li>     
    </ul>

</div>
<?php }?>