<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->head?>
        <?php echo $this->headTitle($this->translate('Bulk SMS'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/intlTelInput.css'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.mod.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.mod.css'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-datetimepicker.min.css')?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/jquery.validate.min.js'))      
            ->prependFile($this->basePath('js/intlTelInput.min.js'))      
            ->prependFile($this->basePath('js/bootstrap.js'))
            ->prependFile($this->basePath() . '/js/bootstrap-datetimepicker.min.js')
            ->prependFile($this->basePath() . '/js/moment.min.js')
            ->prependFile($this->basePath() . '/js/transition.js')
            ->prependFile($this->basePath() . '/js/collapse.js')
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

        
    <style>
    
    .iti-flag {
        background-image: url('<?php echo $this->basePath().'/img/flags.png';?>');
    }
    
    </style>
        
    </head>
    <body>
        
        
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/logo_header.png') ?>" alt="Bulk SMS"/>&nbsp;<?php echo $this->translate('') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav  pull-right">
                        <!--<li class="active"><a href="<?php // echo $this->url('home') ?>"><?php // echo $this->translate('Home') ?></a></li>-->
                        <!--<li ><a href="<?php // echo $this->url('client', array('controller' => 'signup', 'action' => 'index')) ?>"><span class="glyphicon glyphicon-new-window"></span> <?php echo $this->translate('Signup') ?></a></li>-->
                        <!--<li ><a href="<?php // echo $this->url('client/subscription/index'); ?>"><span class="glyphicon glyphicon-log-in"></span> <?php echo $this->translate('Login') ?></a></li>-->
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        
        <!--<div class="container">-->
        <div id="wrap">
        <section style="background: white; min-height: 600px" >
            <!--<div class="container">-->
            
            <div class="container">
                
                <?php echo $this->content;?>
            </div>
            
            <!--</div>-->
        </section>
        </div>
        <!--</div>-->
        
        <div class="container" style="max-height: 60px;">

            <hr style="border-color: #E95E45">
            <footer>
                <table class="table footer-table">
                    <tr>
                        <th>About Us</th>
                        <th>Services</th>
                        <th>FAQ</th>
                        <th>Help</th>
                        <th class="pull-right"><p>&copy; 2005 - <?php echo date('Y') ?> by Some Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p></th>
                    </tr>
                </table>

            </footer>
        </div> <!-- /container -->
        
        <?php echo $this->inlineScript() ?>
        
    </body>
</html>
