
<script>
    $(document).ready(function(){
       $('input').addClass('input-sm');
       $('button').addClass('btn-sm');
    });
</script>

    
<div class="col-lg-8" style="margin-top: 100px;">
<?php
$token = $this->signup_token;
$form = $this->form;
$form->prepare();
$form->setAttribute('action', "/client/signup/complete?token=".$token);

$form->setAttribute('method', 'post');
$form->setAttribute('enctype','multipart/form-data');
$form->setAttribute('class', 'form-horizontal');

echo $this->form()->openTag($form);
?>
    
        <div class="form-group">
            <label></label>
            <div>
                <h2>Set account Password</h2>
                <p>After successful account setup you will be redirected to sign in page.</p>
            </div>
        </div>
        
        <div class="form-group" style="margin-top: 5px;">
            <?php echo $this->formLabel($form->get('password')); ?>
            <div><?php 
                echo $this->formElement($form->get('password'));
                echo $this->formElementErrors($form->get('password'));
            ?></div>
        </div>
        
        <div class="form-group" style="margin-top: 5px;">
            <?php echo $this->formLabel($form->get('confirm_password')); ?>
            <div><?php 
                echo $this->formElement($form->get('confirm_password'));
                echo $this->formElementErrors($form->get('confirm_password'));
            ?></div>
        </div>
        
        <div class="form-group" style="margin-top: 5px;">
            <label></label>
            <div><?php 
            echo $this->formElement($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
        ?></div>
        </div>
        
    
</div>

<?php echo $this->form()->closeTag() ?>
