<table cellspacing="0" cellpadding="0" border="0" style='margin: auto; padding-top: 10px; padding-bottom: 30px; background-color: #15214B; width: 700px; border-left: 25px solid #15214B; border-right: 25px solid #15214B'>
    <tbody>
        <tr >
            <td style="padding:15px 15px 10px 15px;background:#fff;border-radius:4px 4px 0 0; background-color: #15214B;">
                <div>
                    <img src="http://54.93.122.22:2420/logo_header.png" alt="Bulk SMS" height="45" width="149">
                </div>
            </td>
        </tr>
        <tr>
            <td style="padding:15px; background:#fff; border-radius:0 0 4px 4px;font-size:12px">
                <h2 style='font-size: 22px; font-family: arial; color: #4A4A4A;'>We received a request to reset your account password at BulkSMS.com</h2><br><br>
                If you made this request, click the link below. If you didn't make this request, you can ignore this email.<br><br>
                <a href="http://bulk_sms/client/signin/reset?token=<?=$this->token?>" target="_blank"style="color: #005399;text-decoration: none;">http://bulk_sms/client/signin/reset?token=<?=$this->token?></a><br><br>
                Yours, <br>
                BulkSMS.com.<br><br>
                <div style="border-top:3px solid #eee;color:#999;font-size:11px;line-height:1.2">
                    <br>Powered by <a href="http://bulk_sms" target="_blank" style="color: #005399;text-decoration: none;">BulkSMS.com</a>. All rights reserved.<br>
                </div>
            </td>
        </tr>
    </tbody>
</table>
