<script>
$(function(){
    $('select').addClass('input-sm');
    $("input[type!='radio']").addClass('input-sm');
    $('button').addClass('btn-sm');
});
</script>

<div class="col-lg-8" style="margin-top: 100px;">
   
    <h2>Please use one of the following recovery options.</h2>
    <form action="<?php $this->url(NULL, array('controller'=>'Signin', 'action' => 'forgotpassword'));?>" method="post">
        <div class='checkbox'><label><input type="radio" name="fgpass_options" value=1 checked="checked">  I forgot my password</label></div>
        <div class="checkbox"><label><input type="radio" name="fgpass_options" value=2>  I know my password but cannot access it</label></div>
        <div class="col-lg-2">
        <input  type="submit" name="submit" value="Next">
        </div>
        <!--<button name="Cancel" onclick="history.back()">Cancel</button>-->
    </form>
   
</div>
    


