<script>
$(function(){
    $('select').addClass('input-sm');
    $("input[type!='radio']").addClass('input-sm');
    $('button').addClass('btn-sm');
});
</script>
<div class="col-lg-8" style="margin-top: 100px;">
    
    <h2>I know my password, but cannot access it.</h2>
    <p>Tip: double check the account you're trying sign in to. Sometimes people mistype the email address. Also make sure to use correct domain name for your account. </p>
    <button class="col-lg-2" name="login" onclick="window.location.href='index'">OK</button>
    <!--<button name="login" onclick="history.back()">Back</button>-->
    
</div>
