<script>
$(function(){
    $('#resetForm').validate({
        errorPlacement: function (error, element) {
            error.appendTo(element.parent('div').next());
        },
        messages:{
            email: {
                required: "Email ID that you have regiestered with BulkSMS is required.",
                email: "Please enter valid email ID for password reset."
            },
            
        }
    });
    
    
    $('select').addClass('input-sm');
    $("input[type!='radio']").addClass('input-sm');
    $('button').addClass('btn-sm');

    
});
</script>    
<div class="col-lg-5" style="margin-top: 100px;">

    <?php if ( !isset($this->status) ) {?>
        <h2>Get back into your account</h2>
        <p>We can reset your password and security information. First, enter your authorized email address.</p>
        <form action="<?php $this->url(NULL, array('controller'=>'Signin', 'action' => 'recover'));?>" method="post" id="resetForm" class="form-horizontal">
            <div class="form-group">
                <label style="color: #494949">Email Address </label>
                <div><input type="email" name="email" required="required"></div>
            </div>
            <div class="form-group" style="color:red;">
                <label class="col-md-4"></label>
                <div class="col-md-8"><?php echo $this->error;?></div>
            </div>
            
            <div class="form-group">
                <label></label>
                <div><input type="submit" name="submit" value="OK"></div>
            </div>
        
        <!--<input type="submit" name="Cancel" value="Cancel" onclick="window.location.href='/'">-->
        </form>
    <?php } else if ( strcasecmp($this->status, "complete") == 0 ) { ?>
        <h2>Get back into your account</h2>
        <p> Email has been sent to your email account. please login to your email account for password reset.</p>
    <?php }?>

</div>
    
