

<div class='clearfix'></div>
<div class="row" style="margin-top: 50px;">
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Manage Subscriptions') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('Manage multiple subscribers list with single account to get in touch with your friends, family and customers'); ?></p>
                
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Schedule Campaigns') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('Run/Schedule campaign to inform you subscribers latest community updates, news. Invites them to event and/or new offers at your outlets.'); ?></p>
               
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Help &amp; Support') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->translate('Some Technologies is Pakistan’s leading Value-Added-Services & Solutions Provider. Having emerged unparalleled in providing quality services to network operators and consumers across the globe; Some Technology has revolutionized mobile communication into an experience like none other.'); ?></p>
                <p><a class="btn btn-price pull-right" href="http://www.example.com/" target="_blank"><?php echo $this->translate('Contact Us') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
